/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'david' at '10/04/16 13:31' with Gradle 2.8
 *
 * @author david, @date 10/04/16 13:31
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
