/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'david' at '10/04/16 13:31' with Gradle 2.8
 *
 * @author david, @date 10/04/16 13:31
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
